default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: mockit_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: mockit_test
  username: postgres
  password:
  host: localhost
  port: 5432


production:
  <<: *default
  database: mockit_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
