default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: mockit_development
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
  database: mockit_test
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>


production:
  <<: *default
  database: mockit_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
